### ISSUE TITLE
Bullet trajectory presentation

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/Hyperspace#19]
We need a compact way to present the bullet trajectory.

My research using differential equations does not seem to end with a great success, so maybe we need something more simple.

One example is presentation of current calculated trajectory as a group of Bezier curves.

**Comment by ForNeVeR** [comment]
I believe we won't be able to create completely analytical solution for that kind of problem, so here's the list of other possibilities to consider:

- [Verlet integration method](https://en.wikipedia.org/wiki/Verlet_integration)
- [Lennard-Jones potential](https://en.wikipedia.org/wiki/Lennard-Jones_potential)
- Event-driven collision model
- [Fast multipole method](https://en.wikipedia.org/wiki/Fast_multipole_method)

**Comment by ForNeVeR** [comment]
Nah, just send an array of trajectory points from the server to the client, and that's it.

**Comment by rexim** [comment]
Хуяк-хуяк

**Comment by ForNeVeR** [comment]
For now let's just send an array of trajectory points from the server to the client, and that's it.

In case we'll want to implement some optimizations later, we'll reopen the issue.
